In [ ]:
# Import Data
from pathlib import Path

from eis_analysis.system_utilities.file_io import load_file

# "D:\Online\ASU Dropbox\Jacob Clenney\Work Docs\Data\Analysis\IS\EVA\DC Analysis\rnd 2\converted_data.xlsx"
data_file = Path(
    r"D:\Online\ASU Dropbox\Jacob Clenney\Work Docs\Data\Analysis\IS\EVA\DC Analysis\rnd 2"
)

all_loaded_raw_data = {}
for file in ["converted_data.xlsx", "converted_100_and_301.xlsx"]:
    all_loaded_raw_data.update(load_file(data_file / file)[0])

print("Data loaded successfully.")
print(f"Total number of data points: {len(all_loaded_raw_data)}")
print(f"Data keys (ignoring runs): {set(k.split('_')[0] for k in all_loaded_raw_data.keys())}")

Data loaded successfully.
Total number of data points: 162
Data keys (ignoring runs): {'100dh80c', '300dry70c', '301dh60c', '200dh85c', '200dry70c', '300dry85c', '301dh85c', '200pre80c', 'cln2pre70c', '301dh65c', '100pre80c', '200pre70c', 'cln2dh60c', '100dry85c', 'cln2dh80c', 'cln2dry60c', '301dry85c', 'cln2pre85c', '200pre85c', '301dry65c', '301dh80c', '200dry65c', '200dh70c', '300dry80c', '100dry60c', '100dry70c', '100dh60c', '100dry80c', '100pre75c', 'cln2dry80c', '301dry60c', '301dh75c', '100dh85c', 'cln2dry70c', 'cln2dry75c', '100dh75c', '301pre60c', 'cln2dry85c', '300dry60c', '301dry80c', '301dry75c', '301pre70c', '100dry65c', '200dry80c', 'cln2dh70c', '301dry70c', '100dry75c', '100dh70c', '200dh80c', 'cln2dry65c', '100pre60c', 'cln2pre60c', '200dry75c', '100pre65c', '100dh65c', '100pre85c', '200dry60c', '200pre60c', '301dh70c', '200dh60c', '301pre85c', 'cln2dh85c', 'cln2pre80c', '301pre80c', '100pre70c', '200dry85c'}

In [3]:
# Segmenting loop
from eis_analysis.dc_fit.periodicity_detection import (
    process_segments_mean,
)

means_df, seg_arrays_dict, full_arrays_dict = process_segments_mean(all_loaded_raw_data)

print(f"Processed {len(means_df)} segments successfully.")
# print(f"Total segments: {sum(len(v) for v in all_segments.values())}")

Processed 720 segments successfully.

In [4]:
# Parsing section
from eis_analysis.dc_fit.column_parsing import evaluate_segments

results = evaluate_segments(means_df)

In [46]:
results[0]

                                         Voltage       Current    Resistance  \
sample_name condition temp run segment
100         pre       60.0 r1  0        2.001412  4.679348e-11  4.277361e+10
                               1       -2.000824 -4.318292e-11  4.633718e+10
                               2        2.001478  4.681086e-11  4.275954e+10
                               3       -2.000735 -4.322028e-11  4.629489e+10
                           r2  0        2.001600  4.679213e-11  4.277930e+10
...                                          ...           ...           ...
cln2        dry       85.0 r6  3       -2.000953 -1.929327e-10  1.037114e+10
                           r7  0        2.001324  1.833008e-10  1.091804e+10
                               1       -2.000969 -1.933697e-10  1.034790e+10
                               2        2.001392  1.838568e-10  1.088573e+10
                               3       -2.000731 -1.941589e-10  1.030459e+10

                                        Temperature  Voltage rms  \
sample_name condition temp run segment
100         pre       60.0 r1  0          60.405033     2.830427
                               1          60.308947    -2.829590
                               2          60.391960     2.830509
                               3          60.285141    -2.829461
                           r2  0          59.788227     2.830685
...                                             ...          ...
cln2        dry       85.0 r6  3          83.372143    -2.829768
                           r7  0          83.872173     2.830296
                               1          83.839320    -2.829794
                               2          83.947250     2.830394
                               3          83.728731    -2.829466

                                         Current rms  Voltage abs  \
sample_name condition temp run segment
100         pre       60.0 r1  0        6.617597e-11     2.001412
                               1       -6.106987e-11     2.000824
                               2        6.620055e-11     2.001478
                               3       -6.112270e-11     2.000735
                           r2  0        6.617407e-11     2.001600
...                                              ...          ...
cln2        dry       85.0 r6  3       -2.728480e-10     2.000953
                           r7  0        2.592264e-10     2.001324
                               1       -2.734661e-10     2.000969
                               2        2.600127e-10     2.001392
                               3       -2.745822e-10     2.000731

                                         Current abs  raw_Voltage  \
sample_name condition temp run segment
100         pre       60.0 r1  0        4.679348e-11     2.001412
                               1        4.318292e-11    -2.000824
                               2        4.681086e-11     2.001478
                               3        4.322028e-11    -2.000735
                           r2  0        4.679213e-11     2.001600
...                                              ...          ...
cln2        dry       85.0 r6  3        1.929327e-10    -2.000953
                           r7  0        1.833008e-10     2.001324
                               1        1.933697e-10    -2.000969
                               2        1.838568e-10     2.001392
                               3        1.941589e-10    -2.000731

                                        raw_Current  raw_Resistance  \
sample_name condition temp run segment
100         pre       60.0 r1  0                NaN    4.277361e+10
                               1                NaN    4.633718e+10
                               2                NaN    4.275954e+10
                               3                NaN    4.629489e+10
                           r2  0                NaN    4.277930e+10
...                                             ...             ...
cln2        dry       85.0 r6  3                NaN    1.037114e+10
                           r7  0                NaN    1.091804e+10
                               1                NaN    1.034790e+10
                               2                NaN    1.088573e+10
                               3                NaN    1.030459e+10

                                        raw_Temperature  raw_Voltage rms  \
sample_name condition temp run segment
100         pre       60.0 r1  0               0.012491         2.830427
                               1               0.012451        -2.829590
                               2               0.012486         2.830509
                               3               0.012441        -2.829461
                           r2  0               0.012235         2.830685
...                                                 ...              ...
cln2        dry       85.0 r6  3               0.022044        -2.829768
                           r7  0               0.022252         2.830296
                               1               0.022238        -2.829794
                               2               0.022283         2.830394
                               3               0.022192        -2.829466

                                        raw_Current rms  raw_Voltage abs  \
sample_name condition temp run segment
100         pre       60.0 r1  0           6.617597e-11              NaN
                               1          -6.106987e-11              NaN
                               2           6.620055e-11              NaN
                               3          -6.112270e-11              NaN
                           r2  0           6.617407e-11              NaN
...                                                 ...              ...
cln2        dry       85.0 r6  3          -2.728480e-10              NaN
                           r7  0           2.592264e-10              NaN
                               1          -2.734661e-10              NaN
                               2           2.600127e-10              NaN
                               3          -2.745822e-10              NaN

                                        raw_Current abs  multiplier  \
sample_name condition temp run segment
100         pre       60.0 r1  0                    NaN         1.0
                               1                    NaN         1.0
                               2                    NaN         1.0
                               3                    NaN         1.0
                           r2  0                    NaN         1.0
...                                                 ...         ...
cln2        dry       85.0 r6  3                    NaN         1.0
                           r7  0                    NaN         1.0
                               1                    NaN         1.0
                               2                    NaN         1.0
                               3                    NaN         1.0

                                        t_multiplier  demods_1.sample.y  \
sample_name condition temp run segment
100         pre       60.0 r1  0               100.0                NaN
                               1               100.0                NaN
                               2               100.0                NaN
                               3               100.0                NaN
                           r2  0               100.0                NaN
...                                              ...                ...
cln2        dry       85.0 r6  3               100.0                NaN
                           r7  0               100.0                NaN
                               1               100.0                NaN
                               2               100.0                NaN
                               3               100.0                NaN

                                        demods_0.sample.auxin0.fft.abs
sample_name condition temp run segment
100         pre       60.0 r1  0                                   NaN
                               1                                   NaN
                               2                                   NaN
                               3                                   NaN
                           r2  0                                   NaN
...                                                                ...
cln2        dry       85.0 r6  3                                   NaN
                           r7  0                                   NaN
                               1                                   NaN
                               2                                   NaN
                               3                                   NaN

[720 rows x 20 columns]

In [ ]:
# import pandas as pd

# parsed_df = seg_arrays_dict[('100', 'pre', 60.0, 'r1', 0)]
# combined_seg = pd.concat(seg_arrays_dict, axis=0)
# combined_seg.loc[("100", "pre", 60.0, "r1", 0)]

C:\Users\j2cle\AppData\Local\Temp\ipykernel_46952\2505311979.py:4: PerformanceWarning: indexing past lexsort depth may impact performance.
  combined_seg.loc[('100', 'pre', 60.0, 'r1', 0)]

,time_seconds,demods_0.sample.auxin0,demods_0.sample.auxin1,demods_0.sample.y,demods_1.sample.y,imps_0.sample.realz,demods_0.sample.auxin0.fft.abs,demods_0.sample.r,demods_1.sample.r
time,,,,,,,,,
0.000000,0.000000,1.032527,0.012202,9.130134e-10,0.789455,1.493444e+10,NaN,NaN,NaN
0.333333,0.333333,2.001532,0.012258,2.465505e-10,2.830578,1.806138e+10,NaN,NaN,NaN
0.666667,0.666667,2.001539,0.012207,8.160439e-11,2.830582,3.466463e+10,NaN,NaN,NaN
1.000000,1.000000,2.001627,0.012256,7.968661e-11,2.830700,3.552633e+10,NaN,NaN,NaN
1.500000,1.500000,2.001573,0.012248,7.824831e-11,2.830663,3.617729e+10,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
57.000000,57.000000,2.001311,0.012712,6.621792e-11,2.830305,4.275078e+10,NaN,NaN,NaN
57.500000,57.500000,2.001287,0.012723,6.614624e-11,2.830238,4.279021e+10,NaN,NaN,NaN
58.000000,58.000000,2.001331,0.012547,6.621561e-11,2.830312,4.274686e+10,NaN,NaN,NaN
58.500000,58.500000,2.001370,0.012472,6.616611e-11,2.830313,4.277859e+10,NaN,NaN,NaN
59.000000,59.000000,2.001483,0.012537,6.608361e-11,2.830481,4.283441e+10,NaN,NaN,NaN

In [5]:
# Build segmented DataFrame from parsed data
from eis_analysis.dc_fit.column_parsing import apply_col_mapping

base_segments_dict = apply_col_mapping(seg_arrays_dict, results[0], results[1])

In [56]:
# # Optional: Downselect samples before fitting
# from eis_analysis.dc_fit.extract_responses import partial_selection

# base_segments_dict = partial_selection(base_segments_dict, "100")

# print("Only evaluating items with '100' in the index.")
base_segments_dict

{('100',
  'pre',
  60.0,
  'r1',
  0):            time_seconds   Voltage       Current    Resistance  Temperature  \
 time
 0.000000       0.000000  1.032527  6.455980e-10  1.493444e+10    59.707936
 0.333333       0.333333  2.001532  1.743375e-10  1.806138e+10    59.843373
 0.666667       0.666667  2.001539  5.770302e-11  3.466463e+10    59.719313
 1.000000       1.000000  2.001627  5.634694e-11  3.552633e+10    59.837314
 1.500000       1.500000  2.001573  5.532991e-11  3.617729e+10    59.818783
 ...                 ...       ...           ...           ...          ...
 57.000000     57.000000  2.001311  4.682314e-11  4.275078e+10    60.937260
 57.500000     57.500000  2.001287  4.677245e-11  4.279021e+10    60.963373
 58.000000     58.000000  2.001331  4.682151e-11  4.274686e+10    60.539754
 58.500000     58.500000  2.001370  4.678650e-11  4.277859e+10    60.357834
 59.000000     59.000000  2.001483  4.672817e-11  4.283441e+10    60.515907

            Voltage rms   Current rms  Voltage abs   Current abs  raw_Voltage  \
 time
 0.000000      0.789455  9.130134e-10     1.032527  6.455980e-10     1.032527
 0.333333      2.830578  2.465505e-10     2.001532  1.743375e-10     2.001532
 0.666667      2.830582  8.160439e-11     2.001539  5.770302e-11     2.001539
 1.000000      2.830700  7.968661e-11     2.001627  5.634694e-11     2.001627
 1.500000      2.830663  7.824831e-11     2.001573  5.532991e-11     2.001573
 ...                ...           ...          ...           ...          ...
 57.000000     2.830305  6.621792e-11     2.001311  4.682314e-11     2.001311
 57.500000     2.830238  6.614624e-11     2.001287  4.677245e-11     2.001287
 58.000000     2.830312  6.621561e-11     2.001331  4.682151e-11     2.001331
 58.500000     2.830313  6.616611e-11     2.001370  4.678650e-11     2.001370
 59.000000     2.830481  6.608361e-11     2.001483  4.672817e-11     2.001483

             raw_Current  raw_Resistance  raw_Temperature  raw_Voltage rms  \
 time
 0.000000   6.455980e-10    1.493444e+10         0.012202         0.789455
 0.333333   1.743375e-10    1.806138e+10         0.012258         2.830578
 0.666667   5.770302e-11    3.466463e+10         0.012207         2.830582
 1.000000   5.634694e-11    3.552633e+10         0.012256         2.830700
 1.500000   5.532991e-11    3.617729e+10         0.012248         2.830663
 ...                 ...             ...              ...              ...
 57.000000  4.682314e-11    4.275078e+10         0.012712         2.830305
 57.500000  4.677245e-11    4.279021e+10         0.012723         2.830238
 58.000000  4.682151e-11    4.274686e+10         0.012547         2.830312
 58.500000  4.678650e-11    4.277859e+10         0.012472         2.830313
 59.000000  4.672817e-11    4.283441e+10         0.012537         2.830481

            raw_Current rms  raw_Voltage abs  raw_Current abs
 time
 0.000000      9.130134e-10         1.032527     6.455980e-10
 0.333333      2.465505e-10         2.001532     1.743375e-10
 0.666667      8.160439e-11         2.001539     5.770302e-11
 1.000000      7.968661e-11         2.001627     5.634694e-11
 1.500000      7.824831e-11         2.001573     5.532991e-11
 ...                    ...              ...              ...
 57.000000     6.621792e-11         2.001311     4.682314e-11
 57.500000     6.614624e-11         2.001287     4.677245e-11
 58.000000     6.621561e-11         2.001331     4.682151e-11
 58.500000     6.616611e-11         2.001370     4.678650e-11
 59.000000     6.608361e-11         2.001483     4.672817e-11

 [128 rows x 17 columns],
 ('100',
  'pre',
  60.0,
  'r1',
  1):             time_seconds   Voltage       Current    Resistance  Temperature  \
 time
 59.500000       0.000000 -0.013039 -4.152639e-10 -7.725688e+09    60.540696
 60.000000       0.500000 -2.000845 -7.614059e-11  2.691092e+10    60.412846
 60.500000       1.000000 -2.000757 -5.521109e-11  3.626904e+10    60.473812
 61.000000       1.500000 -2.000780 -5.281602e-11  3.787229e+10    60.549736
 61.500000       2.000000 -2.000929 -5.142714e-11  3.891106e+10    60.510030
 ...                  ...       ...           ...           ...          ...
 117.000000     57.500000 -2.000830 -4.313074e-11  4.639409e+10    60.531105
 118.000000     58.500000 -2.000864 -4.306289e-11  4.645408e+10    60.249356
 118.500000     59.000000 -2.000842 -4.312625e-11  4.639811e+10    60.421061
 119.000000     59.500000 -2.000786 -4.302309e-11  4.650885e+10    60.137525
 119.333333     59.833333 -2.000754 -4.306638e-11  4.646060e+10    60.062373

             Voltage rms   Current rms  Voltage abs   Current abs  raw_Voltage  \
 time
 59.500000      0.436198 -5.872719e-10     0.013039  4.152639e-10    -0.013039
 60.000000     -2.829647 -1.076790e-10     2.000845  7.614059e-11    -2.000845
 60.500000     -2.829517 -7.808027e-11     2.000757  5.521109e-11    -2.000757
 61.000000     -2.829532 -7.469313e-11     2.000780  5.281602e-11    -2.000780
 61.500000     -2.829691 -7.272896e-11     2.000929  5.142714e-11    -2.000929
 ...                 ...           ...          ...           ...          ...
 117.000000    -2.829643 -6.099608e-11     2.000830  4.313074e-11    -2.000830
 118.000000    -2.829649 -6.090013e-11     2.000864  4.306289e-11    -2.000864
 118.500000    -2.829624 -6.098973e-11     2.000842  4.312625e-11    -2.000842
 119.000000    -2.829568 -6.084383e-11     2.000786  4.302309e-11    -2.000786
 119.333333    -2.829499 -6.090506e-11     2.000754  4.306638e-11    -2.000754

              raw_Current  raw_Resistance  raw_Temperature  raw_Voltage rms  \
 time
 59.500000  -4.152639e-10   -7.725688e+09         0.012548         0.436198
 60.000000  -7.614059e-11    2.691092e+10         0.012494        -2.829647
 60.500000  -5.521109e-11    3.626904e+10         0.012520        -2.829517
 61.000000  -5.281602e-11    3.787229e+10         0.012551        -2.829532
 61.500000  -5.142714e-11    3.891106e+10         0.012535        -2.829691
 ...                  ...             ...              ...              ...
 117.000000 -4.313074e-11    4.639409e+10         0.012544        -2.829643
 118.000000 -4.306289e-11    4.645408e+10         0.012427        -2.829649
 118.500000 -4.312625e-11    4.639811e+10         0.012498        -2.829624
 119.000000 -4.302309e-11    4.650885e+10         0.012380        -2.829568
 119.333333 -4.306638e-11    4.646060e+10         0.012349        -2.829499

             raw_Current rms  raw_Voltage abs  raw_Current abs
 time
 59.500000     -5.872719e-10         0.013039     4.152639e-10
 60.000000     -1.076790e-10         2.000845     7.614059e-11
 60.500000     -7.808027e-11         2.000757     5.521109e-11
 61.000000     -7.469313e-11         2.000780     5.281602e-11
 61.500000     -7.272896e-11         2.000929     5.142714e-11
 ...                     ...              ...              ...
 117.000000    -6.099608e-11         2.000830     4.313074e-11
 118.000000    -6.090013e-11         2.000864     4.306289e-11
 118.500000    -6.098973e-11         2.000842     4.312625e-11
 119.000000    -6.084383e-11         2.000786     4.302309e-11
 119.333333    -6.090506e-11         2.000754     4.306638e-11

 [128 rows x 17 columns],
 ('100',
  'pre',
  60.0,
  'r1',
  2):             time_seconds   Voltage       Current    Resistance  Temperature  \
 time
 119.666667      0.000000 -1.542827 -3.386737e-11  4.681885e+10    60.170187
 120.000000      0.333333  2.001375  1.866451e-10  1.747717e+10    60.113617
 120.500000      0.833333  2.001384  5.953462e-11  3.358988e+10    60.298691
 121.000000      1.333333  2.001415  5.634351e-11  3.552576e+10    60.434817
 121.500000      1.833333  2.001448  5.516209e-11  3.627332e+10    60.162605
 ...                  ...       ...           ...           ...          ...
 177.000000     57.333333  2.001388  4.683078e-11  4.273996e+10    60.373981
 177.500000     57.833333  2.001399  4.680778e-11  4.276125e+10    60.277945
 178.000000     58.333333  2.001375  4.676687e-11  4.278378e+10    60.253470
 178.500000     58.833333  2.001461  4.674707e-11  4.281779e+10    60.497411
 179.000000     59.333333  2.001389  4.673532e-11  4.282582e+10    60.235487

             Voltage rms   Current rms  Voltage abs   Current abs  raw_Voltage  \
 time
 119.666667    -2.828123 -4.789569e-11     1.542827  3.386737e-11    -1.542827
 120.000000     2.830351  2.639560e-10     2.001375  1.866451e-10     2.001375
 120.500000     2.830419  8.419467e-11     2.001384  5.953462e-11     2.001384
 121.000000     2.830420  7.968175e-11     2.001415  5.634351e-11     2.001415
 121.500000     2.830491  7.801098e-11     2.001448  5.516209e-11     2.001448
 ...                 ...           ...          ...           ...          ...
 177.000000     2.830437  6.622872e-11     2.001388  4.683078e-11     2.001388
 177.500000     2.830419  6.619620e-11     2.001399  4.680778e-11     2.001399
 178.000000     2.830399  6.613835e-11     2.001375  4.676687e-11     2.001375
 178.500000     2.830521  6.611034e-11     2.001461  4.674707e-11     2.001461
 179.000000     2.830351  6.609373e-11     2.001389  4.673532e-11     2.001389

              raw_Current  raw_Resistance  raw_Temperature  raw_Voltage rms  \
 time
 119.666667 -3.386737e-11    4.681885e+10         0.012394        -2.828123
 120.000000  1.866451e-10    1.747717e+10         0.012370         2.830351
 120.500000  5.953462e-11    3.358988e+10         0.012447         2.830419
 121.000000  5.634351e-11    3.552576e+10         0.012504         2.830420
 121.500000  5.516209e-11    3.627332e+10         0.012391         2.830491
 ...                  ...             ...              ...              ...
 177.000000  4.683078e-11    4.273996e+10         0.012478         2.830437
 177.500000  4.680778e-11    4.276125e+10         0.012438         2.830419
 178.000000  4.676687e-11    4.278378e+10         0.012428         2.830399
 178.500000  4.674707e-11    4.281779e+10         0.012530         2.830521
 179.000000  4.673532e-11    4.282582e+10         0.012421         2.830351

             raw_Current rms  raw_Voltage abs  raw_Current abs
 time
 119.666667    -4.789569e-11         1.542827     3.386737e-11
 120.000000     2.639560e-10         2.001375     1.866451e-10
 120.500000     8.419467e-11         2.001384     5.953462e-11
 121.000000     7.968175e-11         2.001415     5.634351e-11
 121.500000     7.801098e-11         2.001448     5.516209e-11
 ...                     ...              ...              ...
 177.000000     6.622872e-11         2.001388     4.683078e-11
 177.500000     6.619620e-11         2.001399     4.680778e-11
 178.000000     6.613835e-11         2.001375     4.676687e-11
 178.500000     6.611034e-11         2.001461     4.674707e-11
 179.000000     6.609373e-11         2.001389     4.673532e-11

 [128 rows x 17 columns],
 ('100',
  'pre',
  60.0,
  'r1',
  3):        time_seconds   Voltage       Current    Resistance  Temperature  \
 time
 179.5           0.0  0.068473 -3.999259e-10  2.369571e+10    60.606316
 180.0           0.5 -2.000825 -2.480055e-10  1.162540e+10    60.362646
 180.5           1.0 -2.000781 -5.540498e-11  3.614622e+10    60.468007
 181.0           1.5 -2.000766 -5.282637e-11  3.787807e+10    60.410226
 181.5           2.0 -2.000761 -5.145403e-11  3.888759e+10    60.169871
 ...             ...       ...           ...           ...          ...
 237.5          58.0 -2.000829 -4.319473e-11  4.632362e+10    60.234530
 238.0          58.5 -2.000896 -4.322135e-11  4.629704e+10    60.305034
 238.5          59.0 -2.000851 -4.323106e-11  4.628617e+10    60.463211
 239.0          59.5 -2.000785 -4.322671e-11  4.628834e+10    60.237814
 239.5          60.0 -2.000802 -4.311291e-11  4.641151e+10    60.254698

        Voltage rms   Current rms  Voltage abs   Current abs  raw_Voltage  \
 time
 179.5     0.550988 -5.655806e-10     0.068473  3.999259e-10     0.068473
 180.0    -2.829607 -3.507327e-10     2.000825  2.480055e-10    -2.000825
 180.5    -2.829552 -7.835447e-11     2.000781  5.540498e-11    -2.000781
 181.0    -2.829502 -7.470777e-11     2.000766  5.282637e-11    -2.000766
 181.5    -2.829526 -7.276699e-11     2.000761  5.145403e-11    -2.000761
 ...            ...           ...          ...           ...          ...
 237.5    -2.829565 -6.108657e-11     2.000829  4.319473e-11    -2.000829
 238.0    -2.829684 -6.112422e-11     2.000896  4.322135e-11    -2.000896
 238.5    -2.829617 -6.113795e-11     2.000851  4.323106e-11    -2.000851
 239.0    -2.829512 -6.113180e-11     2.000785  4.322671e-11    -2.000785
 239.5    -2.829539 -6.097086e-11     2.000802  4.311291e-11    -2.000802

         raw_Current  raw_Resistance  raw_Temperature  raw_Voltage rms  \
 time
 179.5 -3.999259e-10    2.369571e+10         0.012575         0.550988
 180.0 -2.480055e-10    1.162540e+10         0.012474        -2.829607
 180.5 -5.540498e-11    3.614622e+10         0.012517        -2.829552
 181.0 -5.282637e-11    3.787807e+10         0.012493        -2.829502
 181.5 -5.145403e-11    3.888759e+10         0.012394        -2.829526
 ...             ...             ...              ...              ...
 237.5 -4.319473e-11    4.632362e+10         0.012420        -2.829565
 238.0 -4.322135e-11    4.629704e+10         0.012450        -2.829684
 238.5 -4.323106e-11    4.628617e+10         0.012515        -2.829617
 239.0 -4.322671e-11    4.628834e+10         0.012422        -2.829512
 239.5 -4.311291e-11    4.641151e+10         0.012429        -2.829539

        raw_Current rms  raw_Voltage abs  raw_Current abs
 time
 179.5    -5.655806e-10         0.068473     3.999259e-10
 180.0    -3.507327e-10         2.000825     2.480055e-10
 180.5    -7.835447e-11         2.000781     5.540498e-11
 181.0    -7.470777e-11         2.000766     5.282637e-11
 181.5    -7.276699e-11         2.000761     5.145403e-11
 ...                ...              ...              ...
 237.5    -6.108657e-11         2.000829     4.319473e-11
 238.0    -6.112422e-11         2.000896     4.322135e-11
 238.5    -6.113795e-11         2.000851     4.323106e-11
 239.0    -6.113180e-11         2.000785     4.322671e-11
 239.5    -6.097086e-11         2.000802     4.311291e-11

 [128 rows x 17 columns],
 ('100',
  'pre',
  60.0,
  'r2',
  0):            time_seconds   Voltage       Current    Resistance  Temperature  \
 time
 0.000000       0.000000 -1.577487 -3.769700e-11  4.647982e+10    60.056711
 0.333333       0.333333  2.001543  1.743611e-10  1.807292e+10    59.672325
 0.666667       0.666667  2.001602  5.929500e-11  3.373240e+10    59.706658
 1.000000       1.000000  2.001570  5.624403e-11  3.559110e+10    60.062373
 1.500000       1.500000  2.001552  5.509030e-11  3.633471e+10    59.850332
 ...                 ...       ...           ...           ...          ...
 57.000000     57.000000  2.001595  4.667205e-11  4.287013e+10    60.050864
 57.500000     57.500000  2.001546  4.668747e-11  4.287458e+10    59.991437
 58.000000     58.000000  2.001583  4.671616e-11  4.286974e+10    59.466332
 58.500000     58.500000  2.001532  4.672865e-11  4.283582e+10    59.703127
 59.000000     59.000000  2.001618  4.677144e-11  4.279428e+10    59.672717

            Voltage rms   Current rms  Voltage abs   Current abs  raw_Voltage  \
 time
 0.000000     -2.803455 -5.331161e-11     1.577487  3.769700e-11    -1.577487
 0.333333      2.830611  2.465838e-10     2.001543  1.743611e-10     2.001543
 0.666667      2.830703  8.385579e-11     2.001602  5.929500e-11     2.001602
 1.000000      2.830646  7.954107e-11     2.001570  5.624403e-11     2.001570
 1.500000      2.830624  7.790945e-11     2.001552  5.509030e-11     2.001552
 ...                ...           ...          ...           ...          ...
 57.000000     2.830699  6.600424e-11     2.001595  4.667205e-11     2.001595
 57.500000     2.830657  6.602606e-11     2.001546  4.668747e-11     2.001546
 58.000000     2.830651  6.606662e-11     2.001583  4.671616e-11     2.001583
 58.500000     2.830599  6.608429e-11     2.001532  4.672865e-11     2.001532
 59.000000     2.830728  6.614481e-11     2.001618  4.677144e-11     2.001618

             raw_Current  raw_Resistance  raw_Temperature  raw_Voltage rms  \
 time
 0.000000  -3.769700e-11    4.647982e+10         0.012347        -2.803455
 0.333333   1.743611e-10    1.807292e+10         0.012187         2.830611
 0.666667   5.929500e-11    3.373240e+10         0.012201         2.830703
 1.000000   5.624403e-11    3.559110e+10         0.012349         2.830646
 1.500000   5.509030e-11    3.633471e+10         0.012261         2.830624
 ...                 ...             ...              ...              ...
 57.000000  4.667205e-11    4.287013e+10         0.012344         2.830699
 57.500000  4.668747e-11    4.287458e+10         0.012320         2.830657
 58.000000  4.671616e-11    4.286974e+10         0.012102         2.830651
 58.500000  4.672865e-11    4.283582e+10         0.012200         2.830599
 59.000000  4.677144e-11    4.279428e+10         0.012187         2.830728

            raw_Current rms  raw_Voltage abs  raw_Current abs
 time
 0.000000     -5.331161e-11         1.577487     3.769700e-11
 0.333333      2.465838e-10         2.001543     1.743611e-10
 0.666667      8.385579e-11         2.001602     5.929500e-11
 1.000000      7.954107e-11         2.001570     5.624403e-11
 1.500000      7.790945e-11         2.001552     5.509030e-11
 ...                    ...              ...              ...
 57.000000     6.600424e-11         2.001595     4.667205e-11
 57.500000     6.602606e-11         2.001546     4.668747e-11
 58.000000     6.606662e-11         2.001583     4.671616e-11
 58.500000     6.608429e-11         2.001532     4.672865e-11
 59.000000     6.614481e-11         2.001618     4.677144e-11

 [128 rows x 17 columns],
 ('100',
  'pre',
  60.0,
  'r2',
  1):             time_seconds   Voltage       Current    Resistance  Temperature  \
 time
 59.500000       0.000000 -0.012936 -4.152704e-10  1.789625e+10    59.718276
 60.000000       0.500000 -2.000778 -2.001171e-10  1.523836e+10    59.734011
 60.500000       1.000000 -2.000711 -5.525133e-11  3.624104e+10    59.806135
 61.000000       1.500000 -2.000772 -5.262524e-11  3.801166e+10    59.800335
 61.500000       2.000000 -2.000679 -5.143015e-11  3.890460e+10    59.815002
 ...                  ...       ...           ...           ...          ...
 117.333333     57.833333 -2.000622 -4.311026e-11  4.641053e+10    60.611995
 117.666667     58.166667 -2.000730 -4.312490e-11  4.639710e+10    60.680728
 118.000000     58.500000 -2.000696 -4.316796e-11  4.635054e+10    60.368182
 118.500000     59.000000 -2.000603 -4.318615e-11  4.633030e+10    60.423722
 119.000000     59.500000 -2.000654 -4.313720e-11  4.638317e+10    60.436583

             Voltage rms   Current rms  Voltage abs   Current abs  raw_Voltage  \
 time
 59.500000      0.436188 -5.872810e-10     0.012936  4.152704e-10    -0.012936
 60.000000     -2.829483 -2.830083e-10     2.000778  2.001171e-10    -2.000778
 60.500000     -2.829471 -7.813718e-11     2.000711  5.525133e-11    -2.000711
 61.000000     -2.829501 -7.442333e-11     2.000772  5.262524e-11    -2.000772
 61.500000     -2.829414 -7.273322e-11     2.000679  5.143015e-11    -2.000679
 ...                 ...           ...          ...           ...          ...
 117.333333    -2.829302 -6.096711e-11     2.000622  4.311026e-11    -2.000622
 117.666667    -2.829463 -6.098782e-11     2.000730  4.312490e-11    -2.000730
 118.000000    -2.829431 -6.104872e-11     2.000696  4.316796e-11    -2.000696
 118.500000    -2.829276 -6.107444e-11     2.000603  4.318615e-11    -2.000603
 119.000000    -2.829395 -6.100521e-11     2.000654  4.313720e-11    -2.000654

              raw_Current  raw_Resistance  raw_Temperature  raw_Voltage rms  \
 time
 59.500000  -4.152704e-10    1.789625e+10         0.012206         0.436188

In [6]:
# Build segment dataframes for fitting

from eis_analysis.dc_fit.segment_fitting import clean_segment_data

segments_dict = clean_segment_data(base_segments_dict, stable_voltage=True, smooth=True)

In [58]:
# Build segment dataframes for fitting

from eis_analysis.dc_fit.segment_fitting import fit_preparation

fit_map, fit_params_dict = fit_preparation(
    segments_dict,
    mean_df=results[0],
    fit_raw=False,
    # skipcols=[
    #     "Current abs",
    #     "Current rms",
    #     "Voltage abs",
    #     "Voltage rms",
    #     "Voltage",
    #     "Temperature",
    # ],
    # base_fit_map={
    #     "Current": "double_exp_func",
    #     "Resistance": "double_exp_func",
    # },
    base_scale_map={"Current": ["lin", "lin", "log"]},
)

In [60]:
test = fit_params_dict["Current"]
test

bound                                             lb            p0  \
param                                              A             A
sample_name condition temp run segment
100         pre       60.0 r1  0        1.001166e-11  1.001166e-10
                               1       -2.848652e-10 -2.848652e-11
                               2        1.101539e-11  1.101539e-10
                               3       -1.594755e-09 -1.594755e-10
                           r2  0        1.007322e-11  1.007322e-10
...                                              ...           ...
cln2        dry       85.0 r6  3       -1.196527e-09 -1.196527e-10
                           r7  0        1.052453e-11  1.052453e-10
                               1       -1.172980e-09 -1.172980e-10
                               2        1.139660e-11  1.139660e-10
                               3       -1.761931e-09 -1.761931e-10

bound                                             ub scale       lb   p0  \
param                                              A     A      tau  tau
sample_name condition temp run segment
100         pre       60.0 r1  0        1.001166e-09   lin  0.00001  4.5
                               1       -2.848652e-12   lin  0.00001  4.5
                               2        1.101539e-09   lin  0.00001  4.5
                               3       -1.594755e-11   lin  0.00001  4.5
                           r2  0        1.007322e-09   lin  0.00001  4.5
...                                              ...   ...      ...  ...
cln2        dry       85.0 r6  3       -1.196527e-11   lin  0.00001  4.5
                           r7  0        1.052453e-09   lin  0.00001  4.5
                               1       -1.172980e-11   lin  0.00001  4.5
                               2        1.139660e-09   lin  0.00001  4.5
                               3       -1.761931e-11   lin  0.00001  4.5

bound                                     ub scale            lb  \
param                                    tau   tau             B
sample_name condition temp run segment
100         pre       60.0 r1  0        10.0   lin  4.679348e-12
                               1        10.0   lin -4.318292e-10
                               2        10.0   lin  4.681086e-12
                               3        10.0   lin -4.322028e-10
                           r2  0        10.0   lin  4.679213e-12
...                                      ...   ...           ...
cln2        dry       85.0 r6  3        10.0   lin -1.929327e-09
                           r7  0        10.0   lin  1.833008e-11
                               1        10.0   lin -1.933697e-09
                               2        10.0   lin  1.838568e-11
                               3        10.0   lin -1.941589e-09

bound                                             p0            ub scale
param                                              B             B     B
sample_name condition temp run segment
100         pre       60.0 r1  0        4.679348e-11  4.679348e-10   log
                               1       -4.318292e-11 -4.318292e-12   log
                               2        4.681086e-11  4.681086e-10   log
                               3       -4.322028e-11 -4.322028e-12   log
                           r2  0        4.679213e-11  4.679213e-10   log
...                                              ...           ...   ...
cln2        dry       85.0 r6  3       -1.929327e-10 -1.929327e-11   log
                           r7  0        1.833008e-10  1.833008e-09   log
                               1       -1.933697e-10 -1.933697e-11   log
                               2        1.838568e-10  1.838568e-09   log
                               3       -1.941589e-10 -1.941589e-11   log

[720 rows x 12 columns]

In [ ]:
# Run Fit
from eis_analysis.dc_fit.segment_fitting import fit_segments

fit_df, fit_curves, fit_params = fit_segments(
    segments_dict,
    fit_map=fit_map,
    fit_params_dict=fit_params_dict,
    mean_df=results[0],
    weight_inflect=None,
    fit_type="ls",
    # workers=3,
    # disp=1,
    # verbose=0,
    max_nfev=1e3,
)

In [ ]:
# Flattens the multi-index DataFrames for saving.

# results_df, segments_df, parsed_df, seg_df = flatten_multiindex(
#     results_df, segments_df, parsed_df, seg_df, copy=True
# )

In [ ]:
# Save output
from eis_analysis.system_utilities.file_io import save

# if 0:
#     # save(output_dict, data_file, (data_file/file1).stem + "_points",  file_type="xls")
#     save(output_dict, data_file, (data_file / file1).stem + "_points", file_type="xls")
# save(output_dict, data_file, (data_file/file1).stem + "_points",  file_type="xls")
# save(output_dict, data_file, (data_file / file1).stem + "_points", file_type="xls")

if 0:
    save()  # type: ignore

In [ ]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4], dtype=float)
arr[arr == 0] = 1e-32
print(arr)

[1.e-32 1.e+00 2.e+00 3.e+00 4.e+00]

In [ ]:
import pandas as pd

df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
# dfa = df.loc[:, ["a"]]
# dfa.columns = ["cc"]
# df.get(0)
df.loc[2, "a"] = np.nan
df["c"] = np.nan
df.max().max()

6.0

In [ ]:
df = pd.DataFrame({"a": [1, 2, 3]})
df.max().max()

In [15]:
df = pd.DataFrame(index=[1, 2, 3])
df.get("a", 5)

5

In [ ]:
import numpy as np

arr = np.array([])

In [3]:
vals = [(1, 2), (3, 4), (5, 6)]
list(zip(*vals))

[(1, 3, 5), (2, 4, 6)]

In [ ]:
(1, 2, 3, 4)[1 + 2]

4

In [8]:
5 * (-1e-32) ** (-1)

-5e+32

In [2]:
round(3.2563146, 2)

3.26

In [ ]:
import pandas as pd

df = pd.DataFrame(
    {
        "a": [1, 2, 3, 4],
        "b": [2, 3, 4, 4],
        "c": [1, 3, 5, 7],
        "d": [4, 4, 3, 2],
        "e": [2, 2, 3, 4],
        "f": [2, 2, 3, 4],
    }
)
df.skew(axis=0)

a    0.000000
b   -0.854563
c    0.000000
d   -0.854563
e    0.854563
dtype: float64

In [ ]:
df = pd.DataFrame(
    {
        "a": [1e-1, 2e-1, 3e-5, 4e-1, 5e-1],
        "b": [1e-2, 2e-2, 3e-4, 4e-2, 5e-2],
        "c": [1e-5, 2e-5, 3e-1, 4e-5, 5e-5],
    }
)


df.abs().apply(np.log10).apply(np.ptp)

mask = df.columns[df.abs().apply(np.log10).apply(np.ptp) >= 3]
df[mask]


# df.abs().apply(np.log10).skew(skipna=True).abs()

# mask = df.columns[df.abs().apply(np.log10).skew(skipna=True).abs() > 1.8]

# df[mask]

         a        c
0  0.10000  0.00001
1  0.20000  0.00002
2  0.00003  0.30000
3  0.40000  0.00004
4  0.50000  0.00005

In [ ]:
import numpy as np
import pandas as pd

test = pd.DataFrame(
    {"a": [1, 2, 3], "b": [4, 5, 6], "c": [7, 8, 9]}, dtype=float, index=[10, 11, 12]
)
# test.loc[:, "c"] = 10
# test.loc[0, "c"] = 7
test.loc[:, "d"] = pd.Timestamp.now()
test

      a    b    c                          d
10  1.0  4.0  7.0 2025-08-11 15:38:01.701416
11  2.0  5.0  8.0 2025-08-11 15:38:01.701416
12  3.0  6.0  9.0 2025-08-11 15:38:01.701416

In [ ]:
test2 = pd.Series([1, 2, 3, pd.Timestamp.now()], index=["a", "b", "c", "d"])
test.loc[12] = test2
pd.isna(test.loc[12, "a"])

False

In [49]:
"fit 1 cur pos neg".split()[:2]

['fit', '1']